# Generated by Django 5.0.2 on 2024-06-02 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Estudiante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ci', models.CharField(max_length=20, unique=True)),
                ('apellidos_nombres', models.CharField(max_length=255)),
                ('grado', models.CharField(max_length=50)),
                ('seccion', models.CharField(max_length=2)),
                ('sexo', models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino')], max_length=1)),
                ('edad', models.IntegerField()),
                ('lugar_nac', models.CharField(max_length=100)),
                ('fecha_nac', models.DateField()),
                ('representante', models.CharField(max_length=255)),
                ('ci_representante', models.CharField(max_length=20)),
                ('direccion', models.TextField()),
                ('tlf', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'lem_estudiantes',
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(max_length=255)),
                ('apellidos', models.CharField(max_length=255)),
                ('cedula', models.CharField(max_length=45, unique=True)),
                ('usuario', models.CharField(max_length=150, unique=True)),
                ('contrasena', models.CharField(max_length=128)),
                ('correo', models.EmailField(max_length=254, unique=True)),
                ('telefonos', models.CharField(max_length=255)),
                ('direccion', models.TextField()),
                ('rol', models.CharField(max_length=50)),
                ('profile_photo', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
