# Generated by Django 5.0.2 on 2024-08-29 15:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LEM', '0001_initial'),
    ]

    operations = [
        
       
        migrations.AlterField(
            model_name='estudiante',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        
    ]
