# Generated by Django 5.0.2 on 2024-09-05 21:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LEM', '0002_estudiante_docente_estudiante_notas_and_more'),
    ]

    operations = [
       
        migrations.AddField(
            model_name='estudiante',
            name='docente2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='docente2', to='LEM.usuario'),
        ),
        migrations.AddField(
            model_name='estudiante',
            name='docente3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='docente3', to='LEM.usuario'),
        )
    ]
